stages:
  - generate
  - publish
generate:
  stage: generate
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: ghcr.io/vaskozl/apko@sha256:eafcd0f1885c2f1f14eacfd1152b16ceb32f71925f263c739c8beb37e3a96612
  script:
    - hack/generate-jobs.sh
  variables:
    REPO: ghcr.io/vaskozl/
  artifacts:
    paths:
      - generated-config.yml
builds:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
