stages:
  - generate
  - publish
generate:
  stage: generate
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: ghcr.io/vaskozl/apko@sha256:8605dd9fc68e0823b7e791db20aa8c78f076b0a7ec3caa6603c838ce05b56f31
  script:
    - hack/generate-jobs.sh
  variables:
    REPO: ghcr.io/vaskozl/
  artifacts:
    paths:
      - generated-config.yml
builds:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
