stages:
  - generate
  - publish
generate:
  stage: generate
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: ghcr.io/vaskozl/apko@sha256:9b7dabf9ab1fc99d5408d4ef1cff871c079c131738bf03e16e78f01e60511bb8
  script:
    - hack/generate-jobs.sh
  variables:
    REPO: ghcr.io/vaskozl/
  artifacts:
    paths:
      - generated-config.yml
builds:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
