# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/apko/refs/heads/main/pkg/build/types/schema.json
include: wolfi-base.yaml
contents:
  packages:
  - prometheus-node-exporter=1.11.1-r6
entrypoint:
  command: /usr/bin/node_exporter
vcs-url: https://github.com/prometheus/node_exporter
