#!/bin/sh
# Regenerate the flavors/ matrix: desktop × browser × flatpak.
# Each flavor is a thin wrapper around mesa.yaml that adds the desktop
# compositor, optionally a browser, and optionally flatpak.
#
# Output goes into flavors/ at the repo root. The directory is wiped and
# rebuilt on every run, so the script is the source of truth: edit and
# re-run rather than hand-editing the generated yamls.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/flavors"

DESKTOPS="niri cagebreak labwc"
BROWSERS="firefox chromium nobrowser"
FLATPAKS="flatpak noflatpak"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

emit_desktop_packages() {
  case "$1" in
    niri)
      printf '    - niri\n    - niri-bash-completion\n'
      ;;
    cagebreak)
      printf '    - cagebreak\n'
      ;;
    labwc)
      printf '    - labwc\n'
      ;;
  esac
}

emit_browser_packages() {
  case "$1" in
    firefox)   printf '    - firefox\n' ;;
    chromium)  printf '    - chromium\n' ;;
    nobrowser) : ;;
  esac
}

emit_flatpak_packages() {
  case "$1" in
    flatpak)   printf '    - flatpak\n' ;;
    noflatpak) : ;;
  esac
}

for d in $DESKTOPS; do
  for b in $BROWSERS; do
    for f in $FLATPAKS; do
      file="$OUT_DIR/$d-$b-$f.yaml"
      {
        printf '# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/apko/refs/heads/main/pkg/build/types/schema.json\n'
        printf '# Generated by hack/generate-flavors.sh; do not edit by hand.\n'
        printf 'include: mesa.yaml\n'
        printf 'contents:\n'
        printf '  packages:\n'
        emit_desktop_packages "$d"
        emit_browser_packages "$b"
        emit_flatpak_packages "$f"
      } > "$file"
      echo "wrote $file"
    done
  done
done
