daemon off;

events {
  multi_accept on;
}

# Based on http://sabre.io/baikal/install/
http {
  access_log /dev/stdout;
  error_log /dev/stderr warn;
  server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root   /usr/share/webapps/baikal/html;
    index index.php;

    rewrite ^/.well-known/caldav /dav.php redirect;
    rewrite ^/.well-known/carddav /dav.php redirect;

    charset utf-8;

    location ~ /(\.ht|Core|Specific) {
      deny all;
      return 404;
    }

    location ~ ^(.+\.php)(.*)$ {
      try_files $fastcgi_script_name =404;
      include fastcgi_params;
      fastcgi_split_path_info  ^(.+\.php)(.*)$;
      fastcgi_pass  unix:/run/php-fpm/php-fpm.sock;
      fastcgi_param DOCUMENT_ROOT	$realpath_root;
      fastcgi_param SCRIPT_FILENAME	$realpath_root$fastcgi_script_name;
    }
  }
}
