name: GHCR Cleanup

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '*'
          dry-run: true
          expand-packages: true
          delete-untagged: true
          keep-n-tagged: 80
