name: GHCR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    name: GHCR Cleanup
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: cleanup
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1
        with:
          packages: '*'
          expand-packages: true
          keep-n-tagged: 32
          keep-n-untagged: 8
          token: ${{ secrets.CLEANUP_PAT }}
